# Generated by Django 5.0.6 on 2024-06-18 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='author_name',
        ),
    ]
