# Generated by Django 5.0.6 on 2024-06-19 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_author_blog_author_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-time',)},
        ),
    ]
