# Generated by Django 5.1.2 on 2024-10-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='content',
            new_name='Add_Comment',
        ),
    ]
